#!/bin/bash

# Cloudflare Pages GitHub 集成配置脚本

echo "🔧 Cloudflare Pages GitHub 集成配置"
echo "====================================="
echo ""

# 配置信息
CF_ACCOUNT_ID="b8122ff3f404b8271bc74f4ede888c79"
CF_API_TOKEN="cfat_G7kWybCML7pR84ezyXbzXjGENhiYpTQHPcSzhoBG65cc5723"
GITHUB_REPO="ljia2541/finegrain"
PROJECT_NAME="finegrain"

echo "📋 配置信息："
echo "   Cloudflare Account ID: $CF_ACCOUNT_ID"
echo "   GitHub 仓库: $GITHUB_REPO"
echo "   项目名称: $PROJECT_NAME"
echo ""

# 步骤 1：创建 Cloudflare Pages 项目
echo "📦 步骤 1：创建 Cloudflare Pages 项目..."
echo ""
echo "请在浏览器中访问以下链接手动完成配置："
echo ""
echo "1️⃣ 打开 Cloudflare Dashboard:"
echo "   https://dash.cloudflare.com/$CF_ACCOUNT_ID/pages"
echo ""
echo "2️⃣ 点击「创建项目」→「连接到 Git」"
echo ""
echo "3️⃣ 选择 GitHub 仓库: $GITHUB_REPO"
echo ""
echo "4️⃣ 配置构建设置："
echo "   - 构建命令: npm run build"
echo "   - 构建输出目录: .next"
echo "   - Node.js 版本: 18"
echo ""
echo "5️⃣ 配置环境变量："
echo "   - REPLICATE_API_TOKEN"
echo "   - R2_ACCOUNT_ID"
echo "   - R2_ACCESS_KEY_ID (需要创建 R2 API Token)"
echo "   - R2_SECRET_ACCESS_KEY"
echo "   - R2_BUCKET_NAME"
echo "   - R2_PUBLIC_URL"
echo ""
echo "====================================="
echo "⚠️  注意事项："
echo ""
echo "1. R2 存储桶配置："
echo "   - 需要在 Cloudflare Dashboard 中创建 R2 存储桶"
echo "   - 创建 API Token 用于访问 R2"
echo ""
echo "2. 安全提醒："
echo "   - 不要将 .env.local 提交到 Git"
echo "   - 使用环境变量管理敏感信息"
echo ""
echo "3. 构建配置："
echo "   - Next.js 需要特殊配置"
echo "   - 可以使用 @cloudflare/next-on-pages 适配器"
echo ""
echo "====================================="
echo "需要我生成详细的配置步骤文档吗？"
