#!/bin/bash

# Cloudflare Pages 项目配置脚本

echo "🔧 Cloudflare Pages 自动配置脚本"
echo "====================================="
echo ""

CF_ACCOUNT_ID="b8122ff3f404b8271bc74f4ede888c79"
CF_API_TOKEN="cfat_G7kWybCML7pR84ezyXbzXjGENhiYpTQHPcSzhoBG65cc5723"
GITHUB_REPO="ljia2541/finegrain"
PROJECT_NAME="finegrain"

echo "📋 配置信息："
echo "   Account ID: $CF_ACCOUNT_ID"
echo "   GitHub 仓库: $GITHUB_REPO"
echo "   项目名称: $PROJECT_NAME"
echo ""

# 步骤 1：创建 Pages 项目
echo "📦 步骤 1：创建 Cloudflare Pages 项目..."
echo ""
echo "由于 API Token 权限限制，需要手动完成以下步骤："
echo ""
echo "1️⃣ 打开浏览器，访问："
echo "   https://dash.cloudflare.com/$CF_ACCOUNT_ID/pages/view/create"
echo ""
echo "2️⃣ 选择「连接到 Git」"
echo ""
echo "3️⃣ 授权 Cloudflare 访问 GitHub"
echo ""
echo "4️⃣ 选择仓库：$GITHUB_REPO"
echo ""
echo "5️⃣ 配置构建设置："
echo "   - 构建命令：npm run build"
echo "   - 构建输出目录：选择「使用智能默认值」"
echo "   - 根目录：/ (根目录)"
echo ""
echo "6️⃣ 点击「保存并部署」"
echo ""
echo "====================================="
echo ""
echo "⚠️  注意："
echo "- 首次部署可能需要 3-5 分钟"
echo "- 构建日志可以在「部署」标签查看"
echo "- 部署完成后会获得一个 *.pages.dev 域名"
echo ""
echo "====================================="
echo "完成后告诉我，我继续下一步配置！"
echo ""
